package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class HashEquiJoin extends Operator {

    private static final long serialVersionUID = 1L;

    private DbIterator child1, child2;
    private JoinPredicate predicate;
    private HashMap<Field, LinkedList<Tuple>> hashMap;
    private Tuple cur1;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public HashEquiJoin(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.child1 = child1;
        this.child2 = child2;
        this.predicate = p;
        hashMap = new HashMap<>();
    }

    public JoinPredicate getJoinPredicate() {
        return predicate;
    }

    public TupleDesc getTupleDesc() {
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }
    
    public String getJoinField1Name()
    {
        return child1.getTupleDesc().getFieldName(predicate.getField1());
    }

    public String getJoinField2Name()
    {
        return child2.getTupleDesc().getFieldName(predicate.getField2());
    }
    
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        child1.open();
        child2.open();

        listIt = null;
        cur1 = null;

        while (child2.hasNext()) {
            Tuple cur2 = child2.next();
            Field key = cur2.getField(predicate.getField2());

            if (key == null) {
                continue;
            }

            if (!hashMap.containsKey(key)) {
                hashMap.put(key, new LinkedList<>());
            }

            hashMap.get(key).add(cur2);
        }
    }

    public void close() {
        super.close();
        child1.close();
        child2.close();

        listIt = null;
        cur1 = null;

        hashMap.clear();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();

        listIt = null;
        cur1 = null;
    }

    transient Iterator<Tuple> listIt = null;

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, there will be two copies of the join attribute in
     * the results. (Removing such duplicate columns can be done with an
     * additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        while (true) {
            if (cur1 == null) {
                if (!child1.hasNext()) {
                    return null;
                }
                cur1 = child1.next();
                Field key = cur1.getField(predicate.getField1());
                if (key == null) {
                    cur1 = null;
                    continue;
                }
                listIt = hashMap.get(key).iterator();
            }

            if (listIt != null && listIt.hasNext()) {
                return Tuple.merge(cur1, listIt.next());
            }

            cur1 = null;
        }
    }

    @Override
    public DbIterator[] getChildren() {
        return new DbIterator[] {child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        child1 = children[0];
        child2 = children[1];
    }
    
}
